openapi: 3.1.0
info:
  title: Ingestion Service
  description: |
    The Ingestion Service manages data synchronisation between the source database
    and the search index. It handles full index rebuilds and incremental updates.

tags:
  - name: Data
    description: Index data management operations
  - name: Operations
    description: Health and monitoring endpoints

paths:
  /api/refresh:
    post:
      tags:
        - Data
      summary: Full index refresh
      description: |
        Performs an asynchronous refresh of the search index by re-ingesting all records
        from the data source. This is a long-running operation that rebuilds the entire index.

        Use this operation when:
        - Initial index population is needed
        - Index corruption is suspected
        - Schema changes require a full rebuild
      operationId: refresh
      responses:
        "200":
          description: Refresh initiated successfully

  /api/sync:
    post:
      tags:
        - Data
      summary: Sync specific records
      description: |
        Synchronises the search index for specific records identified by their external IDs.
        Use this for incremental updates when only certain records have changed.

        This is more efficient than a full refresh when updating a small number of records.
      operationId: sync
      parameters:
        - name: externalIds
          in: query
          description: External IDs of records to synchronise
          required: true
          schema:
            type: array
            items:
              type: string
          example:
            - EXT-123
            - EXT-456
      responses:
        "200":
          description: Sync completed successfully

  /api/size:
    get:
      tags:
        - Data
      summary: Get index size
      description: Returns the total number of documents currently stored in the search index.
      operationId: getIndexSize
      responses:
        "200":
          description: Index size returned successfully
          content:
            application/json:
              schema:
                type: integer
                format: int64
              example: 1000000

  /actuator/health:
    get:
      tags:
        - Operations
      summary: Health check
      description: Returns the health status of the service.
      operationId: health
      responses:
        "200":
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"
              example:
                status: UP

  /actuator/health/liveness:
    get:
      tags:
        - Operations
      summary: Liveness probe
      description: Kubernetes liveness probe endpoint.
      operationId: liveness
      responses:
        "200":
          description: Service is alive
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"
              example:
                status: UP

  /actuator/health/readiness:
    get:
      tags:
        - Operations
      summary: Readiness probe
      description: Kubernetes readiness probe endpoint.
      operationId: readiness
      responses:
        "200":
          description: Service is ready
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"
              example:
                status: UP

  /actuator/prometheus:
    get:
      tags:
        - Operations
      summary: Prometheus metrics
      description: Returns metrics in Prometheus format.
      operationId: prometheus
      responses:
        "200":
          description: Metrics returned successfully
          content:
            text/plain:
              schema:
                type: string
              example: |
                # HELP jvm_memory_used_bytes The amount of used memory
                # TYPE jvm_memory_used_bytes gauge
                jvm_memory_used_bytes{area="heap"} 1.234567E8

components:
  schemas:
    HealthResponse:
      type: object
      description: Health check response
      properties:
        status:
          type: string
          description: Health status
          enum:
            - UP
            - DOWN
          example: UP
